2017/04/10/removeduplicates.cpp

Make sure to set all bits in wipelast_mask by specifying -1.  (This seems to have been fixed in the blog post itself!)
Starting at out + 1 doesn't detect duplicates in the first two entries
(unless old were set to out[0] instead of out[0] - 1) and makes every
load into an unaligned load.  Just start at out instead.
Check the results of each run to make sure we've got things working.

Fix a few bugs with avx_unique().

---

2018/02/20/Makefile
2018/02/20/bitmapdecode.c

A two, naive-like methods; also slower.

Implementation of block-iterations methods

---

2018/02/20/bitmapdecode.c

Check out the commit message for details.
Below are timings from Skylake - for higher fill factors the assembly code is faster:
$ make && ./bitmapcode  | grep -v callback | grep ctz
make: 'bitmapcode' is up to date.
bitmap_decode_ctz(bitmap, N, receiver)                          :  5.298 cycles per operation (best)    9.721 cycles per operation (avg)
bitmap_decode_ctz__asm(bitmap, N, receiver)                     :  8.402 cycles per operation (best)    11.034 cycles per operation (avg)
bitmap_decode_ctz(bitmap, N, receiver)                          :  5.911 cycles per operation (best)    7.187 cycles per operation (avg)
bitmap_decode_ctz__asm(bitmap, N, receiver)                     :  5.985 cycles per operation (best)    7.089 cycles per operation (avg)
bitmap_decode_ctz(bitmap, N, …

Assembly version with BMI1 instructions

---

2019/03/20/fastestrng.cpp

That helps to evaluate the rng algorithms instead of branch prediction.

Same unroll for all loops

---

extra/fastflags/countbits.cpp

Daniel, I fixed the new procedure; the timings from Skylake machine - seems to be a bit faster:
```
500000 500000 500000 500000 500000 500000 499968 499968 499968 499776 499712 499712 499712 499712 492096 491520 
scalar_naive(array, len, counter)                 	:  3.057 cycles per input word (best)  3.076 cycles per input word (avg) 
scalar_morenaive(array, len, counter)             	:  2.570 cycles per input word (best)  2.580 cycles per input word (avg) 
fastavx2(array, len, counter)                     	:  1.160 cycles per input word (best)  1.170 cycles per input word (avg) 
morefastavx2(array, len, counter)                 	:  1.148 cycles per input word (best)  1.157 cycles per input word (avg) 
flag_stats_avx2(array, len, counter)              	:  3.040 cycles per input word …
```

Fixed popcount-based code

---

2019/04/17/hexparse.cpp

The procedure:
* parses 16 hex digits at once --- the result is uint64_t
* validates input (which is disabled, because I didn't know how to report errors)
* perhaps require some tackling of input (reverse of input)

Parse 16-digit hex string with SSE

---

2019/04/17/hexparse.cpp

Daniel, I created another SSE variant of hex converter. As the previous version, it also detects errors.

Another, simpler SSE variant

---

2018/03/07/simdbitmapdecode.c

Based on https://stackoverflow.com/a/36949578/1218408.
On SKL I'm getting significantly better performance than the other SIMD versions with clang 6+ and your current build params. GCC needs either `-funroll-loops` or manual loop unrolling to bring this on-par with the fastest SIMD versions, but clang still beats GCC because GCC insists on unnecessarily zeroing the popcnt dest register.
```
[bitmap decoding]
bitmap density 0.03  
bitmap_decode_ctz(bitmap, N, receiver)                          :  2.330 cycles per operation (best)    3.334 cycles per operation (avg) 
bitmap_decode_avx2(bitmap, N, receiver)                         :  8.581 cycles per operation (best)    9.831 cycles per operation (avg) 
bitmap_decode_avx2_turbo(bitmap, N, receiver)                   :  9.450 cycles per …
```

Add compressed LUT + verpmd version

---

2020/01/14/alloc.cpp

centralising timing
same for memory fence hack
pulling out constants
formatting into clean columns

code and output clean up

---

extra/memcpyspeed.c

#47: Fix warning implicit declaration of posix_memalign

---

2020/09/10/benchmark.cpp

Variance calculation was wrong, would always report +/- 2.5% (because 2.5 is 100 / 40).

fix variance calculation

---

2017/09/18/inverse.c

Yeah, I know this is kind of too small to even consider, but I got confused when I first saw it, so decided to fix it. 30 isn't above 32.

Minor multiplicative inverse fix

---

2022/09/14/CMakeLists.txt
2022/09/14/bench.cpp
2022/09/14/escape.cpp
2022/09/14/escape.h
2022/09/14/test.cpp

Following up on your Reddit post, I wanted to see how size affected performance. 
I added support to cmake, tests with googletests and benchmarks too.

Added google tests, google benchmarks, and CMake support

---

2022/12/29/protocol.cpp

- Shiftxor is a perfect hash for protocol names with a xor of two shifts.
- Mulhi magic is switched for shorter generation of constants on ARM.
- Both assume little-endian architecture.

Add shiftxor, modify mulhi

---

2022/12/29/protocol.cpp

- Make dfa_is_special read eight bytes efficiently from the buffer.
- Add a pointer-based DFA on basis of earlier indexing DFA.
- This consumes 26 KiB for lookup tables which is completely impractical but demonstrates in the form of dfa3_is_special how a purely pointer-chasing DFA would work, limited only by the load latency and instruction parallelism.
- Reordered states for optimal comparison instruction generation.

add a pure pointer chasing DFA

---

2024/04/13/module/gcd.h

close #96
Tested in <https://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=9101937#2>.
I do not benchmark new codes because I do not have the same environment.

Fix binary_extended_gcd

---

2024/04/13/module/gcd.h

fix <https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/pull/97#issuecomment-2056936031>

Fix corner cases of binary_extended_gcd

---

2024/04/13/benchmarks/benchmark.cpp
2024/04/13/module/gcd.h

fix: add example data & avoid signed overflow

---

2024/10/14/src/main/java/me/lemire/MyBenchmark.java

This is to further show how bad branch misses can be - even beyond what's been reported by https://lemire.me/blog/2024/10/14/table-lookups-are-efficient/
i.e. `0.7 GB/s	1.0 GB/s` for Zen 4 which is my own machine here:
```
Benchmark                                (size)  (specialCharPercentage)   Mode  Cnt      Score      Error  Units
MyBenchmark.benchReplaceBackslash1        65536                        3  thrpt   20  37982.718 ± 1313.768  ops/s
MyBenchmark.benchReplaceBackslash1        65536                       50  thrpt   20  15154.815 ±  618.354  ops/s
MyBenchmark.benchReplaceBackslash2        65536                        3  thrpt   20  23247.763 ±  966.433  ops/s
MyBenchmark.benchReplaceBackslash2        65536                       50  thrpt   20   7128.902 ±  301.891  ops/s …
```

Making probability of special chars configurable

---

2024/10/14/src/main/java/me/lemire/MyBenchmark.java

This is producing some interesting results, although is not yet optimized as it deserves, on my Intel Machine ` 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz` (yet to try with Ryzen, which has a much better branch predictor and can catch up much quickly in case of mispredict - but not on recent firmware changes,see https://chipsandcheese.com/p/turning-off-zen-4s-op-cache-for-curiosity for details)
```
Benchmark                                                      (size)  (specialCharPercentage)   Mode  Cnt        Score    Error      Units
MyBenchmark.benchReplaceBackslashTable3                         65536                       60  thrpt   20     4566.917 ± 24.556      ops/s
MyBenchmark.benchReplaceBackslash3                         	65536                       60  thrpt   20 …
```

Batch read/process/write

---

2024/10/14/src/main/java/me/lemire/MyBenchmark.java

Fixing an error which makes some digits to be considered - since the branchless version body just believe them to be populated

Fix error on tail computation
