2015/01/08/unarydecoding.cpp
Hi Daniel!
I was trying your unary decoding code and found an important issue trivial to fix. Decoding zeros was not working and all values were +1 because bit length was not fully counted ( just newval instead of newval + 1).
You can verify by decoding
data[1] { ( 1 << 1 ) | ( 1 << 0 ) }  // should give { 0, 0 } but was giving { 0, 1 } !!
or
data[2] { 1, 1 }  // should give { 0, 63 } but was giving { 0, 64 } !!
This shouldn't affect benchmarks significantly.
While there I also removed an unused variable.
Cheers,
Ale
=> Fixes for unary decoding

2016/10/10/.gitignore, 2016/10/10/Makefile, 2016/10/10/pcg.h, 2016/10/10/shuffle.cpp
Daniel, this is my attempt to AVX512 shuffling. The procedure works, but is not faster than scalar version, because vectorized code must generate 16 unique indices. This requirement adds extra checks which kill performance.
Moreover, on KNL std::shuffle is eight times slower than your approach (for C-strings and ints). Well done!
Here are numbers from KNL 7210:
```
$ ./shuffle_avx512 
Shuffling arrays of size 1000 
Time reported in number of cycles per array element.
Tests assume that array is in cache as much as possible.
sizeof(string)=32 
sizeof(char *)=8 
shuffle std::string
std::shuffle(testvalues.begin(),testvalues.end(),pgcgen)    :  390.20 cycles per input key 
shuffle_pcg(testvalues.data(),size)                         :  338.79 cycles per input key …
```
=> shuffling: AVX512F + AVX512CD variant for int32_t

2017/04/10/removeduplicates.cpp
Nice AVX2 code to remove duplicates. Here's my attempt to improve it a little bit.
The first three instructions can be replaced by a blend between old and
newval. movemask_ps works fine on integers. Avoid conversion to float
by just casting operands. Use uint32_t everywhere to avoid sign
extension instructions.
=> remove duplicates: use blend and avoid type conversions

2017/07/10/despacer.h
vget_lane_u64 is the best way to get uint64_t form neon type
=> Make all versions of gcc and clang happy

2018/01/31/randomsample.js
The "mix" algorithm doesn't need a (bit-) set. 
See my [comment](https://lemire.me/blog/2018/01/31/picking-distinct-numbers-at-random-benchmarking-a-brilliant-algorithm-javascript-edition/#comment-296174).
For me, it is faster than fastsampleS except for the last case ("Sampling 1000000 values in [0,1000000)."), but probably because it's not using floating point, and not because the lack of set. Not using a set has other advantages: it saves memory.
=> Add "mix" approach

2018/10/16/src/main/java/me/lemire/microbenchmarks/algorithms/Utf8Validate.java
Here we add 3x and 4x stream versions of the DFA approach. Both are considerably faster than the 2x approach, but between the two which one is faster seems to vary based on N and some other factors I'm not exactly clear on. It seems to be at about the limit, I don't expect a 5x version to speed things up much. The Java code generation is not very optimal: so if you did this in C I think you could do more streams and get a higher speedup, probably faster than 2 cycles per byte. There is a "speed limit" here of 1.5 cycles per byte, no matter how many streams, since each transition needs 3 loads and you can do at most 2 loads per cycle. 
You could perhaps break that speed limit by doing the loads from the string 8 at a time (QWORD) and then shifting and masking to grab a byte at a time. Or …
=> triple and quad stream versions

2019/09/05/reference.cpp
Looks like adding the restrict keyword to arrays pointer fixes the speed issue with reference
=> Test with restrict flag

2020/01/14/alloc.cpp, 2020/01/14/run_with_huge_pages.sh
I feel like I understand from the C++ POV what these performance variations were. There are no weird unexplained artefacts any more. 
It is clear that `hugepages` helps massively with fresh allocations and that is also understandable. 
It is not yet clear to me why we cannot seem to get >50% of the theoretical hardware bandwidth while initialising a fresh allocation (ie `malloc` followed by `memset` or just `calloc`). I get about 6.5GB/s on a machine which theoretically supports 12.8GB/s. More hardware/kernel knowledge would be required to answer that. 
But this is not a C++ issue nor something C++ can do much about (apart from ensuring that your application is deployed with hugepages perms which gets you from 25% to 50% of the theoretical maximum). 
Agreed?
=> just small tweaks

.gitignore
Git will ignore all binary executables, as describe in #49.
=> #49: Git will ignore all binary executables

2020/09/23/CMakeLists.txt
UBSAN is much faster than -ftrapv on GCC.
=> added overflow checks with UBSAN

2021/11/17/Makefile, 2021/11/17/convert.cpp
The AVX2 version uses... bigtable and the gather instruction. The new version of SSE2 employs `pshufb`. :)
Here are numbers from the Skylake machine
```
$ ./convert 
khuong     7.6338
backlinear 30.6444
linear 24.2012
tree   15.8183
treet  7.62964
treebt 3.3095
sse2   5.3775
sse2(2) 5.07938
avx2    2.46725
khuong     7.62549
backlinear 30.6456
linear 24.1972
tree   15.8215
treet  7.62947
treebt 3.30961
sse2   5.37789
sse2(2) 5.07852
avx2    2.46616
khuong     7.6303
backlinear 30.6491
linear 24.1959
tree   15.8192
treet  7.6307
treebt 3.30958
sse2   5.37734
sse2(2) 5.07795
avx2    2.46578
```
=> Add slightly better SSE2 version and new AVX2 implementation

2013/12/26/gcd.cpp
Benchmarks weren't using the range offset, so they were showing same results for both number ranges.  Results from updated benchmark:
```
gcd between numbers in [1 and 2000]
Running tests... Ok!
Kops/ms (larger values are better).
basicgcd                    50
gcdwikipedia2               20.3046
gcdwikipedia2fast           44.4444
gcd_recursive               50
gcd_iterative_mod           48.1928
gcdFranke                   46.5116
gcdwikipedia3fast           45.4545
gcdwikipedia4fast           61.5385
gcdwikipedia5fast           44.9438
gcdwikipedia2fastswap       43.0108
gcdwikipedia7fast           48.1928
gcdwikipedia7fast32         76.9231
gcdwikipedia8Spelvin        64.5161
gcd between numbers in [1000000001 and 1000002000]
Running tests... Ok!
Kops/ms (larger values are better). …
```
=> Fix binary GCD benchmark

2022/12/29/protocol.cpp
- Specialised DFA which matches NUL-terminated protocol names, reading up to 6 bytes from the buffer.
- dfa terminates when it sees NUL, dfa_is_special always reads six bytes but ignores everything after string termination.
- dfa2 combines both: reads from string six times but doesn't progress beyond first NUL.
- Default simulation size is too small to differentiate these, branch predictors may learn correct branches for the brancy version.
=> add DFA tests

.gitignore, 2023/02/01/str.cpp
Hi Daniel,
Just for fun, I added a variant implementation of Zukowski's version.
On my M2 mac, it gives these results below (see Zukowski by oc line), 
just a little slower than Zukowski's version but using only 1280 bytes
and just a little faster than the "thin table" version.
And I chose to append . character to string instead of prepending it. 
Regards and keep up the very good work with your blog.
```
Running tests.
Functions are ok.
Time per string in ns.
std::to_string (1)  138.552
std::to_string (2)  143.018
blog post (similar) 29.6376
blog post           28.8351
Dimov 1             19.0179
Dimov 2             29.8581
Zukowski            6.86423
Zukowski by oc      6.90387
thin table          7.39256
```
=> ip to string experimentation

2023/02/01/str.cpp
Pack integer string size on top bits of the 4-byte string, saving one memory lookup at the cost of couple extra ALU ops.
=> add packed lookup table method

2023/07/13/Makefile, 2023/07/13/benchmarks/benchmark.cpp, 2023/07/13/include/sse_type.h, 2023/07/13/scripts/upper_hash.c, 2023/07/13/src/sse_upper_type.c, 2023/07/13/tests/unit.cpp
For simdzone I want to have the name in the descriptor table padded, but as RRTYPEs are normally upper case I wanted to make sure it's not significantly slower. Turns out, it's slightly faster:
```
sse_type                       :   0.97 GB/s  257.3 Ma/s   3.89 ns/d   3.86 GHz  15.01 c/d  41.00 i/d    4.0 c/b  10.87 i/b   2.73 i/c 
sse_upper_type                 :   0.98 GB/s  258.9 Ma/s   3.86 ns/d   3.86 GHz  14.92 c/d  43.00 i/d    4.0 c/b  11.40 i/b   2.88 i/c 
sse_table                      :   0.96 GB/s  254.1 Ma/s   3.93 ns/d   3.86 GHz  15.21 c/d  47.00 i/d    4.0 c/b  12.46 i/b   3.09 i/c 
simple_trie                    :   0.19 GB/s   50.3 Ma/s  19.88 ns/d   3.84 GHz  76.41 c/d  39.00 i/d   20.3 c/b  10.34 i/b   0.51 i/c 
bsearch                        :   0.06 GB/s   15.7 Ma/s …
```
=> Implement sse_type for upper case

2023/08/pending/Makefile, 2023/08/pending/benchmarks/benchmark.cpp, 2023/08/pending/include/name_to_dnswire.h, 2023/08/pending/src/scalar_labels.c, 2023/08/pending/tests/unit.cpp
There's still some warnings in there that I'll fix asap, but preliminary results show `name_to_dnswire_simd` is the faster algorithm.
```
./benchmark top-1m.csv
loaded 1000000 names
average length 25.656 bytes/name
name_to_dnswire_simd           :   2.09 GB/s   81.4 Ma/s  12.29 ns/d   3.88 GHz  47.75 c/d  112.92 i/d    1.9 c/b   4.40 i/b   2.36 i/c 
name_to_dnswire_scalar_labels  :   1.37 GB/s   53.3 Ma/s  18.76 ns/d   3.88 GHz  72.84 c/d  119.15 i/d    2.8 c/b   4.64 i/b   1.64 i/c 
name_to_dnswire                :   0.64 GB/s   24.9 Ma/s  40.20 ns/d   3.88 GHz  156.06 c/d  258.38 i/d    6.1 c/b  10.07 i/b   1.66 i/c
```
=> Add scalar label algorithm for benchmarking

2023/08/09/benchmarks/benchmark.cpp, 2023/08/09/include/name_to_dnswire.h, 2023/08/09/src/name_to_dnswire.c
**work-in-progress**
Domain names, at least in zone data, may contain escape sequences. For that reason, reading in fixed blocks poses a problem. This attempt leverages the fact that labels cannot exceed 63 octets by checking for overlong labels using a bitmap.
```
$ ./benchmark top-1m.csv
loaded 1000000 names
average length 25.5398 bytes/name
name_to_dnswire_idx_avx is simdjson-like
name_to_dnswire_avx is Prefix-Minimum
name_to_dnswire is conventional
name_to_dnswire_idx_avx512     :   1.75 GB/s   68.5 Ma/s  14.60 ns/d   3.78 GHz  55.15 c/d  79.48 i/d    2.2 c/b   3.11 i/b   1.44 i/c 
name_to_dnswire_idx_avx        :   1.83 GB/s   71.6 Ma/s  13.97 ns/d   3.88 GHz  54.16 c/d  87.08 i/d    2.1 c/b   3.41 i/b   1.61 i/c 
name_to_dnswire_loop           :   1.55 GB/s   60.8 Ma/s  16.45 ns/d …
```
=> Alternative version of name_to_dnswire_idx_avx

2023/07/13/Makefile, 2023/07/13/benchmarks/benchmark.cpp, 2023/07/13/include/sse_type.h, 2023/07/13/src/upper_type.c, 2023/07/13/tests/unit.cpp
I intend to use fast [prefix matching](https://lemire.me/blog/2023/07/14/recognizing-string-prefixes-with-simd-instructions/) to detect SvcParamKey's in the SVCB RRTYPE too but didn't feel like implementing a giant switch for the non-SIMD parser. So, I figured why not simply use two `uint64_t`'s as the hash is only calculated over the first 64 bits. Turns out that with the availability of the length, using two `uint64_t`s is faster than the current upper code (SSE version is even slightly faster).
```
sse_type                       :   1.00 GB/s  265.1 Ma/s   3.77 ns/d   3.86 GHz  14.56 c/d  40.00 i/d    3.9 c/b  10.61 i/b   2.75 i/c 
sse_upper_type                 :   1.01 GB/s  267.0 Ma/s   3.75 ns/d   3.86 GHz  14.46 c/d  42.00 i/d    3.8 c/b  11.14 i/b   2.90 i/c 
swar_upper_len …
```
=> Add length versions for matching string prefixes

2023/11/28/benchmarks/benchmark.cpp, 2023/11/28/include/parseuint8.h, 2023/11/28/src/parseuint8.cpp, 2023/11/28/tests/unit.cpp
This seems a bit silly, as optimizations go, but at least on my machine, it's correct and faster than everything except `parse_uint8_nocheck`
=> Turned a branch into an array

.gitignore, 2024/07/05/README.md, 2024/07/05/SimdHTML.sln, 2024/07/05/benchmark/Benchmark.cs, 2024/07/05/benchmark/benchmark.csproj, 2024/07/05/src/SimdHTML.cs, 2024/07/05/src/SimdHTML.csproj, extra/dotnet/utils/Benchmark/SpeedColumn.cs, extra/dotnet/utils/Utils.csproj
This pull-request includes the following changes. For better reviewing experience, consider using "ignore whitespace" option. Thanks!
C# supports regular (implementing `IEnumerable<T>` interface) and duck-typed enumerators.
Therefore, instead of C++-style custom loop, a regular `foreach (var match in ...` can be used instead.
Additionally, make scanning methods and state mutation ones separate - instance methods on structs take them
by reference, and this tends to, sometimes, make the compiler output worse because it forces struct contents
onto the stack instead of keeping them in registers at all times. This is an area where .NET has significantly closed the gap
with LLVM and GCC starting with version 8, but it is more fragile still, so we have to help it out occasionally.
Notably, …
=> Update .NET benchmark code - simplify and improve performance

2024/10/14/src/main/java/me/lemire/MyBenchmark.java
per invocations call can mess up badly with performance although empty (depends if got DCE) - it's safer to remove it
PTAL @lemire
=> Remove per invocation setup

2021/06/03/generate.py
The `log2` function in the original code was poorly named, giving the confusing result `log2(1) == 0`.
```python
def log2(x):
return len(bin(x)) - 2
```
=> Clean up `digit_count` lookup table generation

2024/10/14/pom.xml, 2024/10/14/src/main/java/me/lemire/MyBenchmark.java
The changes are described in the comments for the pr, but sommarized:
1. more realistic compilation due saving OSR to happen
2. using random with fixed seed to be more predictable across runs
3. enable loop unrolling in the table case
I didn't checked yet if the non table version got the same problem; numbers look incredibly different (as expected) thanks to loop unrolling
=> It improves the test in order to make both reproducible and correct numbers

2024/10/14/src/main/java/me/lemire/MyBenchmark.java
This is the improvement on Intel:
before:
```
Benchmark                                             (size)  (specialCharPercentage)   Mode  Cnt      Score     Error  Units
MyBenchmark.benchReplaceBackslashRawCompressedTable3   65536                        3  thrpt   20  18139.485 ± 264.275  ops/s
MyBenchmark.benchReplaceBackslashRawCompressedTable3   65536                       50  thrpt   20  18368.666 ±  47.128  ops/s
```
after:
```
Benchmark                                             (size)  (specialCharPercentage)   Mode  Cnt      Score    Error  Units
MyBenchmark.benchReplaceBackslashRawCompressedTable3   65536                        3  thrpt   20  19460.961 ± 53.448  ops/s
MyBenchmark.benchReplaceBackslashRawCompressedTable3   65536                       50  thrpt   20  19445.190 ± …
```
=> Precomputed compression mask parts and replacements
